import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet } from '@angular/router';
import { ArticleListeComponent } from "./article/article-liste.component";
import { Article } from './models/article-model';


@Component({
    selector: 'app-root',
    standalone: true,
    templateUrl: './app.component.html',
    styleUrl: './app.component.scss',
    imports: [CommonModule, RouterOutlet, ArticleListeComponent]
})
export class AppComponent {
  title = 'seminaireLerica';
  artcles!: Article[];
  article!: Article;
  ngOnInit(): void {
    this.artcles = [
      new Article("Le 23/04/2024 à 14h à St Charles, FRUMAM, 2ème étage",
      " Sabine Frittella (LIFO, Université d'Orléans)",
      "A venir",
      "A venir"),
      new Article("Le 18/03/2024 à 14h30 (à distance)",
      "Davide Catta (Università degli studi di Napoli, Federico II, DIETI)",
      "Raisonnement sur les modèles de jeux dynamiques à l'aide de logiques d'obstruction",
      "Les logiques d'obstruction sont des logiques temporelles que nous avons récemment introduites. Elles permettent de raisonner sur les propriétés temporelles des jeux dans lesquels un joueur peut modifier la structure topologique d'un graphe orienté en désactivant ses arcs. Dans ce séminaire, nous introduirons les propriétés formelles de ces logiques, en nous concentrant sur le problème du model-checking. Nous montrerons également comment ces logiques permettent d'exprimer des propriétés de cyber-sécurité sur des graphes d'attaque."
      ),
      new Article("Le 18/03/2024 à 13h (à distance)",
      "Daniil Kozhemiachenko (LABRI, Université de Bordeaux)",
      "(Paraconsistent) Expansions of Gödel modal logics",
      "Gödel modal logics on [0,1]-valued frames with possibly fuzzy accessibility relation (i.e., the value of the relation can also be between 0 and 1) were first proposed by Caicedo and Rodriguez in 2010. Since then, they have been further developed by Metcalfe, Olivetti, and Rogger (proof theory and complexity), Vidal (logics on crisp frames), and Godo, Esteva, Rodriguez, and Tuyt (applications to possibility measures). In this talk, we consider KbiG — the expansion of Gödel modal logic with an additional connective — Baaz' Delta or coimplication. We also present KG^2 — the expansion of KbiG with a paraconsistent De Morgan negation. We show how to use these logics to formalise comparative belief statements (e.g., ‘I think that rain is more likely than hailstorm’) and construct Hilbert-style axiomatisations of KbiG and KG^2 and discuss their completeness proofs. We observe that crisp KG^2 expands crisp KbiG but there is no expansion in the fuzzy case. We also cover some results on frame definability and correspondence theory: transfer of crisp frame definability from K (minimal classical normal modal logic) to KbiG, characterisation of finitely branching frames via Glivenko theorem, and the characterisation of formulas transferrable from fuzzy KbiG to fuzzy KG^2 via embedding of the latter into the former. The talk is based on the following papers with Marta Bilkova and Sabine Frittella. Crisp bi-Gödel modal logic and its paraconsistent expansion (IGPL, jzad017); Fuzzy bi-Gödel modal logic and its paraconsistent relatives (JLC, exae011)."
      ),
      new Article("Le 25/03/2024 à 14h à St Charles, FRUMAM, 3ème étage (et à distance)",
      "Van-Giang Trinh (LIS, UMR 7020, LIRICA)",
      "Scalable Enumeration of Trap Spaces in Boolean Networks via Answer Set Programming",
      "Boolean Networks (BNs) are widely used as a modeling formalism in several domains, notably systems biology and computer science. A fundamental problem in BN analysis is the enumeration of trap spaces, which are hypercubes in the state space that cannot be escaped once entered. Several methods have been proposed for enumerating trap spaces, however they often suffer from scalability and efficiency issues, particularly for large and complex models. To our knowledge, the most efficient and recent methods for the trap space enumeration all rely on Answer Set Programming (ASP), which has been widely applied to the analysis of BNs. Motivated by these considerations, our work proposes a new method for enumerating trap spaces in BNs using ASP. We evaluate the method on a mix of 250+ real-world and 400+ randomly generated BNs, showing that it enables analysis of models beyond the capabilities of existing tools (namely pyboolnet, mpbn, trappist, and trapmvn). Reference: Van-Giang Trinh, Belaid Benhamou, Samuel Pastva, & Sylvain Soliman. (2024, February). Scalable enumeration of trap spaces in Boolean networks via answer set programming. In Annual AAAI Conference on Artificial Intelligence. (to appear, oral presentation)"
      ),
      new Article("Le 18/03/2024 à 14h à St Charles, FRUMAM, 2ème étage",
      "Simon Vilmin (LIS, UMR 7020, LIRICA)",
      "Les systèmes de fermeture et leurs représentations",
      "Un système de fermeture sur un univers (fini) X est une famille de sous-ensembles de X, dits fermés, close par intersection et contenant X. Ces systèmes apparaissent dans de nombreux champs de l'informatique et des mathématiques par le biais de représentations implicites. Parmi les représentations possibles, deux sont communes : - les bases d'implications, soit des ensembles de règles A --> b signifiant \"un ensemble contenant l'ensemble A doit contenir l'élément b\" ; - l'ensemble des fermés (inf-)irréductibles, ces derniers étant les fermés à partir duquel reconstruire tout le système. Dans cet exposé, je ferai une introduction générale aux systèmes de fermeture et leurs représentations. Je mentionnerai entre autres quelques-uns des résultats importants en la matière, et je parlerai du problème de passage d’une représentation à l’autre dont la complexité est toujours inconnue à ce jour malgré plus de 30 ans de recherche."
      ),
      new Article("Le 26/02/2024 à 14h à St Charles, FRUMAM, 2ème étage",
      "Faustine Oliva (Centre Gilles Gaston Granger / Laboratoire d'Informatique de Grenoble)",
      "Comment l’hypercarte peut-elle nous guider à travers la démonstration assistée par ordinateur du théorème des quatre couleurs ?",
      "Afin de soumettre la démonstration du théorème des quatre couleurs à l’évaluation de l’assistant de preuve Coq l’énoncé du théorème a dû être reformulé. En effet les deux premières démonstrations (Appel&Haken 1977, 1977, Robertson et al. 1997) s’appuient sur la notion de graphe et recourent à des arguments topologiques qu’on peut difficilement formaliser et utiliser dans le système Coq. C’est pour cette raison que la formalisation de la démonstration dans l’environnement de l’assistant de preuve fait reposer la démonstration du théorème, qui porte originellement sur les cartes planaires, sur la démonstration de sa version combinatoire qui concerne les hypercartes. Le but de cet exposé est de mettre en évidence la manière dont les contraintes exercées par le système Coq -- dont l’une des principales conséquences est de devoir recourir à la notion d’hypercarte -- peuvent avoir un impact sur les propriétés épistémiques et mathématiques de la démonstration obtenue. En d’autres termes il s’agira de déterminer si, en plus de permettre la vérification de la démonstration du théorème des quatre couleurs par un assistant de preuve, cette formalisation nous apprend quelque chose sur la démonstration du théorème et sur le théorème lui-même. À partir d’une analyse de la notion d’expertisabilité telle qu’elle est développée par Tymoczko dans (Tymoczko 1979) nous commencerons par montrer que ce projet de formalisation peut être envisagé comme une quête d’expertisabilité particulière que nous qualifierons d’orientée-ordinateur. Nous introduirons ensuite la notion d’hypercarte, présenterons les avantages qu’elle offre et insisterons sur la manière dont elle est étroitement liée aux différents usages qui peuvent être faits de la modularité. Enfin nous interrogerons la prétention de cette démonstration formalisée à jouer le rôle de preuve du théorème des quatre couleurs. Pour cela nous mettrons en évidence les possibles conflits entre les exigences liées au développement logiciel et celles liées aux mathématiques. Ces possibles conflits trouvent leur source dans la double nature de cette démonstration qui est à la fois une preuve et un programme. Nous présenterons alors une manière de concilier ces exigences en proposant un changement de perspective sur cet objet d’étude : nous défendrons le fait qu’une démonstration assistée par ordinateur peut également être envisagée comme un programme assisté par humain."
      ),
      new Article("Le 08/01/2024 à 14h à St Charles, FRUMAM, 2ème étage",
      "Raïda Ktari (LIS, UMR 7020, LIRICA)",
      "Toward credible belief base revision",
      " We are concerned with belief revision, where several operators have been proposed. Some of them are based on the construction of maximally consistent sub-bases according to set inclusion or cardinality as maximality criterion. These criteria do not always guarantee the selection of the most relevant information and can consequently neglect potential formulas from the agent’s initial beliefs. This work tries to address this problem by investigating a sub-base selection criterion which respects the minimal change principle of belief revision in a sense which seems more credible, while trying to perform the change by capturing the most valuable or potential information from initial beliefs. In order to achieve this goal, we define two formula-based operators similar to RSRG and RSRW (Würbel et al. (2000), Creignou et al. (2017)), namely CSRG and CSRW. These new operators are based on the selection of the most credible consistent sub-bases. The computation of credibility is performed using suitable tools offered by evidence theory (belief functions theory). We study the logical properties of our operators in terms of satisfaction of postulates that should hold for any rational belief base revision operator. This work also investigates the productivity of the inference relation from the revision result as well as the complexity study of model checking problem for these operators."
      ),
      new Article("Le 11/12/2023 à 14h à St Charles, FRUMAM, 3ème étage",
      "Han Gao (LIS, UMR 7020, LIRICA)",
      "Variants of intuitionistic modal logic",
      "Intuitionistic modal logic as a branch of non-classical logic enjoys a long history tracing back to 1940s. In the development since then, two main traditions have emerged, one called intuitionistic modal logic and the other constructive modal logic. These two traditions are motivated by meta-logical properties and applications in computer science respectively.In this seminar, I will first give a brief introduction about the general development of the field of intuitionistic modal logic focusing on some prominent logics like IK, CCDL, CK, etc. Then I will introduce a recent work that reveals intuitionistic modal logics defined by natural variants of Kripke's semantics for which little or no research has been done. I will present the results we obtained so far concerning axiomatization, proof-systems and decidability of some of these logics. Finally, I will also discuss some open problems.## ReferenceP. Balbiani, H. Gao, Ç. Gencer and N. Olivetti, A Natural Intuitionistic Modal Logic: Axiomatization and Bi-nestedCalculus, Computer Science Logic 2024 (CSL'24), to appear."
      ),
      new Article("Le 20/11/2023 à 14h à St Charles, FRUMAM, 3ème étage",
      "Van-Giang Trinh (LIS, UMR 7020, LIRICA)",
      "Efficient enumeration of fixed points in complex Boolean networks using answer set programming",
      "Boolean Networks (BNs) are an efficient modeling formalism with applications in various research fields such as mathematics, computer science, and more recently systems biology. One crucial problem in the BN research is to enumerate all fixed points, which has been proven crucial in the analysis and control of biological systems. Indeed, in that field, BNs originated from the pioneering work of R. Thomas on gene regulation and from the start were characterized by their asymptotic behavior: complex attractors and fixed points. The former being notably more difficult to compute exactly, and specific to certain biological systems, the computation of stable states (fixed points) has been the standard way to analyze those BNs for years. However, with the increase in model size and complexity of Boolean update functions, the existing methods for this problem show their limitations. To our knowledge, all the state-of-the-art methods for the fixed point enumeration problem rely on Answer Set Programming (ASP). Motivated by these facts, in this work we propose two new efficient ASP-based methods to solve this problem. We evaluate them on both real-world and pseudo-random models, showing that they vastly outperform four state-of-the-art methods as well as can handle very large and complex models.## ReferenceVan-Giang Trinh, Belaid Benhamou, and Sylvain Soliman. \"Efficient Enumeration of Fixed Points in Complex Boolean Networks Using Answer Set Programming.\" In 29th International Conference on Principles and Practice of Constraint Programming (CP 2023). Schloss Dagstuhl-Leibniz-Zentrum für Informatik, 2023." 
      ),
      new Article("Le 18/09/2023 à 15h à St Charles, FRUMAM, 2ème étage",
      "Simon Vilmin (LIS, UMR 7020, LIRICA)",
      "Enumération des modèles maximaux d'une formule de Horn",
      "L'énumération des modèles maximaux d'une formule de Horn est un problème difficile qui apparaît implicitement dans plusieurs domaines de l'informatique, allant du data mining à l'optimisation combinatoire.En outre, il généralise la dualisation des fonctions monotones booléennes (ou dualisation des hypergraphes) et se rapporte au problème de dualisation dans les treillis codés par des bases d’implications. Dans cet exposé, je présenterai le problème et quelques résultats connus à son sujet.En général, le problème ne peut être résolu en temps total polynomial à moins que P = NP, ce qui suggère l'étude de cas particuliers.Je m'intéresserai au cas où les clauses négatives de la formule ont taille deux.En tirant parti du lien entre formules de Horn et treillis, j'utiliserai le nombre de Carathéodory et la dualisation des hypergraphes pour donner des classes de formules où le problème peut être résolu en temps total (quasi-)polynomial.Je mentionnerai aussi des classes de treillis où le problème est déjà plus dur que la dualisation des hypergraphes, même si les clauses négatives sont de tailles deux."
      ),
      new Article("Le 03/07/2023 à 14h à St Charles, FRUMAM, 2ème étage",
      "Emiliano Lorini (IRIT)",
      "A Rule-based Modal View of Causal Reasoning",
      "We present a novel rule-based semantics for causal reasoning as well as a number of modal languages interpreted over it. They enable us to represent some fundamental concepts in the theory of causality including causal necessity and possibility, interventionist conditionals and Lewisian conditionals. We provide complexity results for the satisfiability checking and model checking problem for these modal languages. Moreover, we study the relationship between our rule-based semantics and the structural equation modeling (SEM) approach to causal reasoning, as well as between our rule-based semantics for causal conditionals and the standard semantics for belief base change."
      ),
      new Article("Le 05/06/2023 à 10h à St Charles, FRUMAM, 3ème étage",
      "Simon Vilmin (LORIA)",
      "Enumération des modèles maximaux d'une formule de Horn",
      "L'énumération des modèles maximaux d'une formule de Horn est un problème difficile qui apparaît implicitement dans plusieurs domaines de l'informatique, allant du data mining à la logique modale. En outre, il généralise la dualisation des fonctions monotones booléennes (ou dualisation des hypergraphes) et se rapporte au problème de dualisation dans les treillis codés par des bases d’implications. Dans cet exposé, je présenterai le problème et quelques résultats connus à son sujet. En général, le problème ne peut être résolu en temps total polynomial à moins que P = NP, ce qui suggère l'étude de cas particuliers. Je m'intéresserai au cas où les clauses négatives de la formule ont taille deux, qui fait écho au codage d'un graphe médian au moyen d'un ordre partiel et d'un graphe de conflit. En tirant parti du lien entre formules de Horn et treillis, j'utiliserai le nombre de Carathéodory (que l'on retrouve notamment en optimisation combinatoire) et la dualisation des hypergraphes pour donner des classes de formules où le problème peut être résolu en temps total (quasi-)polynomial. Je mentionnerai aussi des classes de treillis où le problème est déjà plus dur que la dualisation des hypergraphes, même si les clauses négatives sont de tailles deux."
      ),
      new Article("Le 15/05/2023 à 14h à St Charles, FRUMAM, 2ème étage",
      " Philippe Balbiani (IRIT)",
      "Unification in non-classical logics",
      " Originally motivated by automatic deduction tools, the unification problem in modal logics constitutes today the heart of an active research area in which much remains to be done. Within the context of description logics, the main motivation for investigating the unification problem was to propose new reasoning services in the maintenance of knowledge bases like the elimination of redundancies in the descriptions of concepts. In this talk, we will give a survey of the results on unification in these non-classical logics and we will present some of the open problems whose solution will have a great impact on the future of the area."
      ),
      new Article("Le 05/05/2023 à 14h30 à St Charles, FRUMAM, 3ème étage",
      "Karim Tabia (CRIL)",
      "Reasoning with Uncertain Inputs in an Imprecise Probabilistic Setting",
      "Probability intervals provide an intuitive, powerful and unifying setting for encoding and reasoning with imprecise beliefs. In this presentation, I will talk about some recent work related to reasoning with uncertain information in the framework of probability intervals. Il will first discuss the problem of updating uncertain information specified in the form of probability intervals with new uncertain inputs also expressed as probability intervals. Secondly, I will discuss the inverse problem of probabilistic belief update with uncertain inputs. Finally, I present an application of reasoning with uncertain information to better calibrate the predictive probabilities of machine learning models."
      ),
      new Article("Le 10/04/2023 à 14h à distance",
      "Samuel Pastva (Institute of Science and Technology, Vienna)",
      "Robust control of Boolean networks in systems biology",
      "Boolean networks represent a simple yet scalable model of gene regulation in living organisms. Their ability to mimic biological systems makes them useful when attempting to reprogram the function of biological circuits (e.g. altering cell phenotypes). Depending on the specific biological conditions, this problem comes in many flavours, but is collectively referred to as Boolean network control. Today, even the most detailed Boolean models often contain elements that are either added ad hoc or fine-tuned (arguably over-fitted) to a particular dataset. An alternative is to view these elements as unknown or undetermined, which is more true to the available biological knowledge. However, this introduces uncertainty in the network dynamics which complicates computational analysis and interpretation of results. This talk provides an overview of the various sub-problems of Boolean network control and methods for addressing these problems computationally. It then expands this view to partially specificed Boolean networks and introduces a notion of robust control which allows to safely account for uncertainty in network dynamics. The viability of robust control is explored using a collection of symbolic, BDD-based algorithms."
      )
    ]
  }
}
